local M = {}

---@param colors ThemeColors
---@param opts   ThemeOptions
---@return table<string, vim.api.keyset.highlight>
function M.get(colors, opts)
    local c = colors

    return {
        SnacksIndent                    = { fg = c.guide },
        SnacksIndentBlank               = { link = 'SnacksIndent' },
        SnacksIndentScope               = { fg = c.guide_active },
        SnacksIndentChunk               = { link = 'SnacksIndentScope' },
        SnacksIndent1                   = { link = 'DiagnosticInfo' },
        SnacksIndent2                   = { link = 'DiagnosticHint' },
        SnacksIndent3                   = { link = 'DiagnosticWarn' },
        SnacksIndent4                   = { link = 'DiagnosticError' },
        SnacksIndent5                   = { link = 'DiagnosticInfo' },
        SnacksIndent6                   = { link = 'DiagnosticHint' },
        SnacksIndent7                   = { link = 'DiagnosticWarn' },
        SnacksIndent8                   = { link = 'DiagnosticError' },

        SnacksPicker                    = { fg = c.fg, bg = c.bg_float },
        SnacksPickerBorder              = { fg = c.border, bg = c.bg_float },
        SnacksPickerBoxBorder           = { fg = c.border, bg = c.bg_float },
        SnacksPickerInput               = { fg = c.fg, bg = c.bg_float },
        SnacksPickerInputBorder         = { fg = c.border, bg = c.bg_float },
        SnacksPickerInputTitle          = { fg = c.accent, bg = c.bg_float, bold = true },
        SnacksPickerList                = { fg = c.fg, bg = c.bg_float },
        SnacksPickerListBorder          = { fg = c.border, bg = c.bg_float },
        SnacksPickerListCursorLine      = { bg = c.bg_selection },
        SnacksPickerPreview             = { fg = c.fg, bg = c.bg_float },
        SnacksPickerPreviewBorder       = { fg = c.border, bg = c.bg_float },
        SnacksPickerPreviewTitle        = { fg = c.sage, bg = c.bg_float, bold = true },
        SnacksPickerPreviewCursorLine   = { bg = c.bg_selection },
        SnacksPickerTitle               = { fg = c.accent, bg = c.bg_float, bold = true },
        SnacksPickerFooter              = { fg = c.fg_dim, bg = c.bg_float },

        SnacksPickerMatch               = { fg = c.accent, bold = true },
        SnacksPickerSearch              = { link = 'Search' },
        SnacksPickerPrompt              = { fg = c.accent },
        SnacksPickerInputSearch         = { link = '@keyword' },
        SnacksPickerSpecial             = { fg = c.teal },
        SnacksPickerLabel               = { link = 'SnacksPickerSpecial' },
        SnacksPickerTotals              = { link = 'NonText' },
        SnacksPickerFile                = { fg = c.fg },
        SnacksPickerDirectory           = { link = 'Directory' },
        SnacksPickerDir                 = { link = 'SnacksPickerFile' },
        SnacksPickerPathIgnored         = { link = 'NonText' },
        SnacksPickerPathHidden          = { link = 'NonText' },
        SnacksPickerDimmed              = { link = 'Conceal' },
        SnacksPickerRow                 = { link = 'String' },
        SnacksPickerCol                 = { link = 'LineNr' },
        SnacksPickerComment             = { link = 'Comment' },
        SnacksPickerDesc                = { link = 'Comment' },
        SnacksPickerDelim               = { link = 'Delimiter' },
        SnacksPickerSpinner             = { fg = c.accent },
        SnacksPickerSelected            = { link = 'Number' },
        SnacksPickerUnselected          = { link = 'NonText' },
        SnacksPickerIdx                 = { link = 'Number' },
        SnacksPickerBold                = { link = 'Bold' },
        SnacksPickerItalic              = { link = 'Italic' },
        SnacksPickerCode                = { link = '@markup.raw.markdown_inline' },
        SnacksPickerRule                = { link = '@punctuation.special.markdown' },
        SnacksPickerTree                = { link = 'LineNr' },
        SnacksPickerLink                = { link = 'Comment' },
        SnacksPickerLinkBroken          = { link = 'DiagnosticError' },
        SnacksPickerToggle              = { link = 'DiagnosticVirtualTextInfo' },
        SnacksPickerPickWin             = { link = 'Search' },
        SnacksPickerPickWinCurrent      = { link = 'CurSearch' },

        SnacksPickerGit                 = { fg = c.git_change },
        SnacksPickerGitCommit           = { link = '@variable.builtin' },
        SnacksPickerGitBreaking         = { link = 'Error' },
        SnacksPickerGitDetached         = { link = 'DiagnosticWarn' },
        SnacksPickerGitBranch           = { link = 'Title' },
        SnacksPickerGitBranchCurrent    = { link = 'Number' },
        SnacksPickerGitDate             = { link = 'Special' },
        SnacksPickerGitIssue            = { link = 'Number' },
        SnacksPickerGitAuthor           = { link = 'Constant' },
        SnacksPickerGitType             = { link = 'Title' },
        SnacksPickerGitScope            = { link = 'Italic' },
        SnacksPickerGitMsg              = { fg = c.fg },
        SnacksPickerGitStatus           = { link = 'Special' },
        SnacksPickerGitStatusAdded      = { link = 'Added' },
        SnacksPickerGitStatusModified   = { link = 'DiagnosticWarn' },
        SnacksPickerGitStatusDeleted    = { link = 'Removed' },
        SnacksPickerGitStatusRenamed    = { link = 'SnacksPickerGitStatus' },
        SnacksPickerGitStatusCopied     = { link = 'SnacksPickerGitStatus' },
        SnacksPickerGitStatusUntracked  = { link = 'NonText' },
        SnacksPickerGitStatusIgnored    = { link = 'NonText' },
        SnacksPickerGitStatusUnmerged   = { link = 'DiagnosticError' },
        SnacksPickerGitStatusStaged     = { link = 'DiagnosticHint' },

        SnacksPickerCmd                 = { link = 'Function' },
        SnacksPickerCmdBuiltin          = { link = '@constructor' },
        SnacksPickerAuPattern           = { link = 'String' },
        SnacksPickerAuEvent             = { link = 'Constant' },
        SnacksPickerAuGroup             = { link = 'Type' },
        SnacksPickerDiagnosticCode      = { link = 'Special' },
        SnacksPickerDiagnosticSource    = { link = 'Comment' },
        SnacksPickerRegister            = { link = 'Number' },
        SnacksPickerKeymapMode          = { link = 'Number' },
        SnacksPickerKeymapLhs           = { link = 'Special' },
        SnacksPickerKeymapNowait        = { link = '@variable.builtin' },
        SnacksPickerKeymapRhs           = { link = 'NonText' },
        SnacksPickerBufNr               = { link = 'Number' },
        SnacksPickerBufFlags            = { link = 'NonText' },
        SnacksPickerBufType             = { link = 'Function' },
        SnacksPickerFileType            = { link = 'DiagnosticHint' },
        SnacksPickerTime                = { link = 'Special' },
        SnacksPickerUndoAdded           = { link = 'Added' },
        SnacksPickerUndoRemoved         = { link = 'Removed' },
        SnacksPickerUndoCurrent         = { link = '@variable.builtin' },
        SnacksPickerUndoSaved           = { link = 'Special' },
        SnacksPickerManSection          = { link = 'Number' },
        SnacksPickerManPage             = { link = 'Special' },
        SnacksPickerManDesc             = { link = 'Comment' },
        SnacksPickerLspDisabled         = { link = 'DiagnosticWarn' },
        SnacksPickerLspEnabled          = { link = 'Special' },
        SnacksPickerLspAttached         = { link = 'DiagnosticWarn' },
        SnacksPickerLspAttachedBuf      = { link = 'DiagnosticInfo' },
        SnacksPickerLspUnavailable      = { link = 'DiagnosticError' },
        SnacksPickerNotificationMessage = { fg = c.fg },

        SnacksPickerIcon                = { link = 'Special' },
        SnacksPickerIconSource          = { link = '@constant' },
        SnacksPickerIconName            = { link = '@keyword' },
        SnacksPickerIconCategory        = { link = '@module' },
        SnacksPickerIconArray           = { link = '@punctuation.bracket' },
        SnacksPickerIconBoolean         = { link = '@boolean' },
        SnacksPickerIconClass           = { link = '@type' },
        SnacksPickerIconConstant        = { link = '@constant' },
        SnacksPickerIconConstructor     = { link = '@constructor' },
        SnacksPickerIconEnum            = { link = '@lsp.type.enum' },
        SnacksPickerIconEnumMember      = { link = '@lsp.type.enumMember' },
        SnacksPickerIconEvent           = { link = 'Special' },
        SnacksPickerIconField           = { link = '@variable.member' },
        SnacksPickerIconFile            = { link = 'Normal' },
        SnacksPickerIconFunction        = { link = '@function' },
        SnacksPickerIconInterface       = { link = '@lsp.type.interface' },
        SnacksPickerIconKey             = { link = '@lsp.type.keyword' },
        SnacksPickerIconMethod          = { link = '@function.method' },
        SnacksPickerIconModule          = { link = '@module' },
        SnacksPickerIconNamespace       = { link = '@module' },
        SnacksPickerIconNull            = { link = '@constant.builtin' },
        SnacksPickerIconNumber          = { link = '@number' },
        SnacksPickerIconObject          = { link = '@constant' },
        SnacksPickerIconOperator        = { link = '@operator' },
        SnacksPickerIconPackage         = { link = '@module' },
        SnacksPickerIconProperty        = { link = '@property' },
        SnacksPickerIconString          = { link = '@string' },
        SnacksPickerIconStruct          = { link = '@lsp.type.struct' },
        SnacksPickerIconTypeParameter   = { link = '@lsp.type.typeParameter' },
        SnacksPickerIconVariable        = { link = '@variable' },

        SnacksDiffHeader                = { link = 'DiagnosticVirtualTextInfo' },
        SnacksDiffAdd                   = { link = 'DiffAdd' },
        SnacksDiffDelete                = { link = 'DiffDelete' },
        SnacksDiffContext               = { link = 'DiffChange' },
        SnacksDiffConflict              = { link = 'DiagnosticVirtualTextWarn' },
        SnacksDiffLabel                 = { link = '@property' },
    }
end

return M
